### ISSUE TITLE
게시물 공유 기능 관련 버그

### ISSUE THREAD

**Issue by jhlim101** [wafflestudio21-5/team5-server#102]
게시물 하단에 있는 공유 버튼이 작동 안되는 것 같습니다! 

<img width="469" alt="Screenshot 2024-02-04 at 2 16 02 AM" src="https://github.com/wafflestudio21-5/team5-server/assets/111844119/7c1a7609-fd96-48c4-982f-2807d707dd2b">

**Comment by jwchoi-kr** [comment]
UI만 있는 것이 맞습니다!ㅎㅎ 감사합니다
