### ISSUE TITLE
[BUG] 다른 사람 팔로워 창에서 뒤로가기 

### ISSUE THREAD

**Issue by JH713** [wafflestudio21-5/team5-server#110]
다른 사람 팔로워 창에 들어갔다 나오면 내 페이지가 나오는 오류가 있습니다.

https://github.com/wafflestudio21-5/team5-server/assets/86519350/0625e40c-9107-4a57-8c45-db112d8f5979

**Comment by jwchoi-kr** [comment]
수정했습니다. 알려주셔서 감사합니다!
