### ISSUE TITLE
새로고침, 프로필 사진 관련 에러

### ISSUE THREAD

**Issue by yknxh** [wafflestudio21-5/team5-server#112]
1. 로그인을 한 상태에서 새로고침을 하면 아예 로그아웃되어 로그인 페이지로 이동합니다.
2. 다른 사람의 프로필 사진을 클릭하면 내 기기의 사진을 업로드하는 창이 뜹니다.

**Comment by jwchoi-kr** [comment]
알려주셔서 감사합니다! 2는 수정했고 1은 수정중입니다
