### ISSUE TITLE
PR merge, branch rebase 관련

### ISSUE THREAD

**Issue by isuh88** [wafflestudio21-5/team5-server#9]
## 🛠️ Problems
기존 feat/feed 브랜치의 경우 제 로컬 작업 상황에서 feat/post, feat/auth를 rebase하여 작업하였습니다. 구현 완료 이후 PR을 생성할 때 충돌 해결을 위해 main을 가져와서 병합하였는데, rebase로 인해 커밋 히스토리가 난잡해지는 것은 물론 github action 적용 이전의 브랜치를 병합한 것이 문제가 되어 CI 테스트에 실패했습니다. 이후 main에서 feat/feedv2 브랜치를 새로 생성하여 로컬에서 작업한 파일을 옮긴 뒤 다시 PR을 생성하였습니다.
## 👍 Proposal
브랜치 전략에 맞게끔 오직 main 브랜치에서만 분기하여 작업하는 것이 커밋 히스토리 및 충돌 해결에 도움이 될 것 같습니다. 또한 병렬적으로 작업을 진행하되 향후 개발할 기능이 의존하게 될 부분은 main에 즉각적으로 반영되어야 할 것 같습니다 :)

**Comment by rayark1** [comment]
https://git-scm.com/book/ko/v2/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-Rebase-%ED%95%98%EA%B8%B0
rebase에 관련된 문서입니다! 본인이 push 한 commit 이외에는 취사선택의 영역인 것 같습니다.

**Comment by SeonghaeJo** [comment]
저 같은 경우 메인 브랜치를 최신화한 다음, 오직 메인 브랜치에서만 분기하여 작업합니다.
작업 중인 브랜치를 커밋했는데, 메인 브랜치가 업데이트된 경우
`git merge main --squash`를 사용하여 squash merge를 선호하는 편입니다.
