### ISSUE TITLE
메인 페이지가 아닌 페이지에서 새로고침을 하면 Access Denied

### ISSUE THREAD

**Issue by ComPhyPark** [wafflestudio21-5/team5-server#97]
세미나 과제를 하면서 비슷한 이슈를 겪은 적이 있는데, aws 배포 시 Cloudfront에서 오류 도메인을 지정하면 해결된다고 합니다
지금은 도메인이 정확히 "waffle5gram.com"일 때만 들어가지고, 아닐 때는 아래처럼 에러 메시지가 떠요
<img width="643" alt="image" src="https://github.com/wafflestudio21-5/team5-server/assets/69303148/fa6e9ae3-ba33-42ff-9b01-c4ddec8211f4">

**Comment by jwchoi-kr** [comment]
오 배워갑니다 감사합니다
